from typing import Protocol

from contact_fiche.entities.fiche_entity import Fiche


class FicheRepository(Protocol):
    def get_by_id(self, id: str) -> Fiche | None: ...
    def save(self, fiche: Fiche) -> None: ...
    def update(self, id: str, fiche: Fiche) -> None: ...
    def delete(self, id:str) -> None: ...